version: "3.1"
services:
  app:
    build: .
    container_name: app
    command: sh -c 'yarn && yarn dev'
    volumes:
      - .:/var/www/app
    depends_on:
      - mongo
      - redis
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      MONGODB_URI: mongodb://mongo:27017/truber-api
      REDIS_URI: redis://redis

  mongo:
    image: mongo
    container_name: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    command: --quiet
    environment:
      MONGO_INITDB_DATABASE: truber-api

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  mongodata:
