version: '3'
services:
  web:
    build: .
    volumes:
      - .:/var/www/app
      - /var/www/app/node_modules
    ports:
    - "5000:5000"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27015:27015"
